[package]
name = "opensrme_sr2"
version = "0.0.1"
authors = ["tzizi"]

[dependencies]
"opensrme_common" = { path = "../common" }
encoding = "0.2"
rand = "*"
byteorder = "1"
crc = "^1.0.0"
nalgebra = "0.16"
ncollide2d = "0.17"

[lib]
name = "opensrme_sr2"
path = "src/lib.rs"